
set(FILES
    Source/Tools/HammerEditorSystemComponent.cpp
    Source/Tools/HammerEditorSystemComponent.h
    Source/Tools/HammerViewportLayoutWidget.cpp
    Source/Tools/HammerViewportLayoutWidget.h
    Source/Tools/HammerViewportLayoutWidget.ui
    Source/Tools/HammerWidget.cpp
    Source/Tools/HammerWidget.h
    Source/Tools/HammerWidget.ui
    Source/Tools/HammerViewportManipulatorController.cpp
    Source/Tools/HammerViewportManipulatorController.h
    Source/Tools/HammerEditorViewportSettings.cpp
    Source/Tools/HammerEditorViewportSettings.h
    Source/Tools/HammerActiveViewportTracker.cpp
    Source/Tools/HammerActiveViewportTracker.h
    Source/Tools/HammerQtEnvironment.h
    Source/Tools/HammerQtEnvironment.cpp
    Source/Tools/HammerRenderViewportWidget.cpp
    Source/Tools/HammerRenderViewportWidget.h
    Source/Tools/HammerViewportCameraFactory.cpp
    Source/Tools/HammerViewportCameraFactory.h
    Source/Tools/Hammer.qrc
)
